---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jolie-disk-writer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jolie-disk-writer
    spec:
      volumes:
        - name: disk-pod
          persistentVolumeClaim:
            claimName: jolie-deployer-disk-claim
      containers:
        - image: "joelhandig/disk_writer"
          imagePullPolicy: Always
          name: jolie-disk-writer
          volumeMounts: 
            - mountPath: "/data"
              name: "disk-pod"
          ports:
            - containerPort: 8020
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: jolie-disk-writer
  namespace: "default"
  labels:
    app: jolie-disk-writer
spec:
  ports:
    - protocol: "TCP"
      port: 8020
      targetPort: 8020
  selector:
    app: jolie-disk-writer
