apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jolie-deployer-disk-claim-read
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
